spring:
  datasource:
    url: jdbc:h2:file:./demodb;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=true
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

graphiql:
  cdn:
    enabled: true
  endpoint:
security:
  token-lifetime: 30m